version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "japanese-holiday-checker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-38q82pkmbade"
s3_prefix = "sam-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
