AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:
  japanese-holiday
Globals:
  Function:
    Timeout: 3

Resources:
  UpdateHolidayDbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: holiday_function
      Handler: holiday/db_update.lambda_handler
      Runtime: python3.9
      Timeout: 90
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 20 * * ? *)'
            Name: UpdateHolidayDbSchedule
            Description: Schedule for Update HolidayDB
            Enabled: True

  HolidayDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties: 
      TableName: "HolidayDB"
      PrimaryKey: 
        Name: Date
        Type: String
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CheckHolidayFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: holiday_function
      Handler: holiday/http_app.lambda_handler
      Runtime: python3.9
      Policies:
      - AmazonDynamoDBReadOnlyAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /check_holiday
            Method: get
            RequestParameters:
              - method.request.querystring.date

Outputs:
  UpdateHolidayDbFunction:
    Description: "Update Holiday DB Lambda Function ARN"
    Value: !GetAtt UpdateHolidayDbFunction.Arn

Metadata:
  AWS::ServerlessRepo::Application:
    Name: japanese-holiday
    Description: Check the date is japanese holiday or not
    Author: Tatsuhiko Kono
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['microservice']
    HomePageUrl: https://github.com/k11o/japanese-holiday
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/k11o/japanese-holiday


